"""Report rendering — the markdown WP5/WP7/WP8 build on.

    python -m harness.report --out results/analysis/REPORT-metrics.md

Reads results/ through metrics.compute() for both tasks and writes one markdown document:
served-model assertion table, per-system metrics, paired differences and the equivalent
Claude tier, cost and latency, and the calibration summary. It states numbers; the
narrative in REPORT.md (WP8) is written by hand on top of it.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Optional

from harness import metrics as M

REPO_ROOT = Path(__file__).resolve().parent.parent


def build(
    *,
    split: str = "test",
    ref: str = "jev",
    rep: Optional[int] = 1,
    root: Optional[Path] = None,
) -> tuple[str, dict[str, Any]]:
    reports: dict[str, Any] = {}
    parts = [
        "# Jev vs Claude — measured results",
        "",
        "Generated by `python -m harness.report`. Every number is recomputed from "
        "`results/<task>/<system>/results.jsonl`; no aggregate field is trusted "
        "(PLAN.md §8, WP7 brief).",
        "",
    ]
    for task in ("task1", "task2"):
        systems = M.discover_systems(task, root)
        if not systems:
            parts += [f"## {task}", "", "_no rows yet_", ""]
            continue
        rep_obj = M.compute(task, split=split, ref=ref, rep=rep, root=root)
        reports[task] = rep_obj
        parts += [M.to_markdown(rep_obj), ""]
        parts += _calibration_section(rep_obj)
        parts += _strata_section(rep_obj, task)
    return "\n".join(parts), reports


def _calibration_section(rep: dict[str, Any]) -> list[str]:
    lines = [f"### Calibration ({rep['task']})", "",
             "| system | ECE | bins with data |", "|---|---:|---:|"]
    any_row = False
    for s, m in rep["systems"].items():
        cal = m.get("calibration") or {}
        if cal.get("ece") is None:
            continue
        any_row = True
        lines.append(f"| {s} | {cal['ece']:.4f} | {len(cal.get('bins') or [])} |")
    return (lines + [""]) if any_row else []


def _strata_section(rep: dict[str, Any], task: str) -> list[str]:
    key = "recall_by_subtype" if task == "task2" else "accuracy_by_stratum"
    strata = sorted({k for m in rep["systems"].values() for k in (m.get(key) or {})})
    if not strata:
        return []
    title = "Recall per subtype" if task == "task2" else "Accuracy per slice"
    lines = [f"### {title} ({task})", "", "| system | " + " | ".join(strata) + " |",
             "|---|" + "---|" * len(strata)]
    for s, m in rep["systems"].items():
        cells = [M._fmt((m.get(key) or {}).get(k)) for k in strata]
        lines.append(f"| {s} | " + " | ".join(cells) + " |")
    return lines + [""]


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(prog="harness.report")
    ap.add_argument("--split", default="test", choices=("train", "test", "all", "variance"))
    ap.add_argument("--ref", default="jev")
    ap.add_argument("--rep", type=int, default=1)
    ap.add_argument("--results-root", type=Path, default=None)
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--json-out", type=Path, default=None)
    args = ap.parse_args(argv)
    md, reports = build(split=args.split, ref=args.ref, rep=args.rep, root=args.results_root)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(md, encoding="utf-8")
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(
            json.dumps(reports, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8"
        )
    if not args.out:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
